import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
// import Sidebar from "@/components/Sidebar";

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "EchoMemo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN" data-theme="cupcake">
      <body
        className={`${comfortaa.variable} m-auto flex min-h-screen flex-col antialiased`}
      >
        <Providers>
          <main className="">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
